import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// import React from "react";
// import { TESelect } from "tw-elements-react";
function Setting() {
    // const data = [
    //   { text: "Light", value: 1 },
    //   { text: "Dark", value: 2 },
    // ];
    return (_jsx("div", { className: "p-4", children: _jsx("div", { className: "flex flex-col p-6 bg-white rounded-lg shadow-md", children: _jsxs("form", { children: [_jsxs("div", { className: "mb-4", children: [_jsx("h2", { className: "text-xl font-medium text-gray-700 mb-2", children: "Account" }), _jsxs("div", { className: "flex flex-col space-y-4", children: [_jsxs("div", { className: "relative mb-6", children: [_jsx("input", { type: "text", className: "peer block w-full rounded border-0 bg-gray-500 px-4 py-3 text-gray-700 placeholder-gray-500 focus:bg-white focus:outline-none dark:bg-gray-100 dark:text-gray dark:placeholder-gray-400", id: "exampleInputUsername", placeholder: "Enter Your Username" }), _jsx("label", { htmlFor: "exampleInputUsername", className: "pointer-events-none absolute left-4 top-0 mb-0 pt-3 leading-6 text-gray-500 transition-all duration-200 ease-out peer-focus:-translate-y-6 peer-focus:scale-75 peer-focus:text-primary dark:text-gray-400", children: "Enter Your Username" })] }), _jsxs("div", { className: "relative mb-6", children: [_jsx("input", { type: "text", className: "peer block w-full rounded border-0 bg-gray-500 px-4 py-3 text-gray-700 placeholder-gray-500 focus:bg-white focus:outline-none dark:bg-gray-100 dark:text-gray dark:placeholder-gray-400", id: "exampleInputUsername", placeholder: "Enter Your Email" }), _jsx("label", { htmlFor: "exampleInputUsername", className: "pointer-events-none absolute left-4 top-0 mb-0 pt-3 leading-6 text-gray-500 transition-all duration-200 ease-out peer-focus:-translate-y-6 peer-focus:scale-75 peer-focus:text-primary dark:text-gray-400", children: "Enter Your Email" })] })] })] }), _jsxs("div", { className: "mb-6", children: [_jsx("h2", { className: "text-xl font-medium text-gray-700 mb-2", children: "Preferences" }), _jsxs("div", { className: "flex flex-col space-y-4", children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "theme", className: "block text-sm font-medium text-gray-600 mb-1", children: "Theme" }), _jsxs("select", { id: "theme", className: "peer block w-full rounded border-0 bg-gray-500 px-4 py-3 text-gray-700 placeholder-gray-500 focus:bg-white focus:outline-none dark:bg-gray-100 dark:text-gray dark:placeholder-gray-400", children: [_jsx("option", { children: "Light" }), _jsx("option", { children: "Dark" })] })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "notifications", className: "block text-sm font-medium text-gray-600 mb-1", children: "Notifications" }), _jsx("input", { id: "notifications", type: "checkbox", className: "mt-1 h-4 w-4 text-teal-500 focus:ring-teal-500 border-gray-300 rounded" }), _jsx("span", { className: "ml-2 text-gray-700", children: "Enable notifications" })] })] })] }), _jsx("button", { type: "submit", className: "w-full px-4 py-2 bg-teal-500 text-white font-semibold rounded-md shadow-md hover:bg-teal-600 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-opacity-50", children: "Save Changes" })] }) }) }));
}
export default Setting;
